### ISSUE TITLE
the game freezes on the loading screen

### ISSUE THREAD

**Issue by lessthanoptima** [Esper89/Subnautica-TerrainPatcher#10]
**Describe the bug:**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Log File**
Please upload your `LogOutput.log` file, located in the `BepInEx` folder.

**Patch Files**
Please upload any relevant `.optoctreepatch` files from the `BepInEx/plugins` folder.

**Please complete the following version information:**
 - Subnautica/Below Zero: Living Large Update/What the Dock Update
 - Terrain Patcher: 1.1.0
 - Other mods...?

**Additional Context**

**Comment by Esper89** [comment]
Please see the [Terrain Extender](https://github.com/Esper89/Subnautica-TerrainPatcher#terrain-extender) section of the readme page.
