### ISSUE TITLE
QMod Failed to Load TerrainPatcher

### ISSUE THREAD

**Issue by BarnacleBenis** [Esper89/Subnautica-TerrainPatcher#3]
Installed as instructed, but QMod Manager failed to load the TerrainPatcher.

[qmodmanager_log-Subnautica.txt](https://github.com/Esper89/Subnautica-TerrainPatcher/files/9286688/qmodmanager_log-Subnautica.txt)

**Comment by Esper89** [comment]
You installed the source code, not the actual mod. To install the mod, download the `.zip` file from the [releases page](https://github.com/Esper89/Subnautica-TerrainPatcher/releases/latest) and extract it to your QMods folder.

**Comment by BarnacleBenis** [comment]
hehe... oops. Thanks...
