### ISSUE TITLE
Subnautica not responding

### ISSUE THREAD

**Issue by IWentLucid** [Esper89/Subnautica-TerrainPatcher#4]
When adding to my qmods folder subnautica just will not run. any fixes?

**Comment by Esper89** [comment]
Can you upload your log file so I can tell what's going wrong? It should be located in the same folder as your `Subnautica.exe`, named `qmodmanager_log-Subnautica.txt`.

**Comment by Esper89** [comment]
~~It seems that this issue is caused by the newest version of Subnautica, which has been released on Steam but not on Epic. I only have Subnautica on Epic, so I can't fix this issue until the update comes to Epic.~~

**Comment by Esper89** [comment]
~~As a workaround, you can go into the game's properties, select the "betas" tab, and switch the branch to "legacy". This should restore the game to the old version that this mod works with, but any new mods that are made for the new version won't be compatible, so this won't work forever.~~

**Comment by Esper89** [comment]
Okay, it turns out this issue *isn't* caused by a new version of the game. Please upload your log file so I can determine the actual problem @IWentLucid.

**Comment by Esper89** [comment]
I'm assuming the issue was resolved.
