### ISSUE TITLE
Blockchain integration urgently needed

### ISSUE THREAD

**Issue by outlineutils** [Esper89/Subnautica-TerrainPatcher#6]
As you may know, the metaverse is surging in popularity, and may potentially overtake the World Wide Web in popularity in the next few years. There is no way Subnautica-TerrainPatcher has a future without additional mechanisms that provide its transparency and availability like Blockchain does. In a strategic decision our institution which has built its entire product variety on this application will move on to Blockchain. Until then I cant implement this as it will negatively affect my stock prices. I will need this done by next week.

**Comment by Esper89** [comment]
go home jenny

**Comment by outlineutils** [comment]
queer
